package main

type Order struct {
	OrdersID                   int      `json:"orders_id"`
	CustomersID                int      `json:"customers_id"`
	DeliveryName               string   `json:"delivery_name"`
	DeliveryTelephone          string   `json:"delivery_telephone"`
	DeliveryAddress            *string  `json:"delivery_address"`
	DeliveryFloor              *string  `json:"delivery_floor"`
	DeliveryCity               *string  `json:"delivery_city"`
	DeliveryPostcode           *string  `json:"delivery_postcode"`
	DeliveryState              *string  `json:"delivery_state"`
	DeliveryCountry            *string  `json:"delivery_country"`
	DeliveryInstruction        *string  `json:"delivery_instruction"`
	PaymentMethod              *string  `json:"payment_method"`
	BillingZip                 *string  `json:"billing_zip"`
	LastModified               *int64   `json:"last_modified"`
	DatePurchased              *int64   `json:"date_purchased"`
	OrdersStatus               int      `json:"orders_status"`
	OrdersDateFinished         *int64   `json:"orders_date_finished"`
	ShippingType               *string  `json:"shipping_type"`
	ConfirmedAt                *int64   `json:"confirmed_at"`
	PaymentStatus              *string  `json:"payment_status"`
	Email                      *string  `json:"email"`
	TipAmount                  *int     `json:"tip_amount"`
	BillingAddress             *string  `json:"billing_address"`
	DeliverAt                  *int64   `json:"deliver_at"`
	ShopID                     *int     `json:"shop_id"`
	ShopUUID                   *string  `json:"shop_uuid"`
	Adjustment                 *int     `json:"adjustment"`
	ForceTotal                 *int     `json:"force_total"`
	CrossStreet                *string  `json:"cross_street"`
	Lat                        *float64 `json:"lat"`
	Lng                        *float64 `json:"lng"`
	Eta                        *string  `json:"eta"`
	ShopSentOrderAt            *int64   `json:"shop_sent_order_at"`
	CustomerEmailedAt          *int64   `json:"customer_emailed_at"`
	ConfirmationAttemptCount   *int     `json:"confirmation_attempt_count"`
	PlacedVia                  *string  `json:"placed_via"`
	DeliveryLocationType       *string  `json:"delivery_location_type"`
	CreatedAt                  *int64   `json:"created_at"`
	UpdatedAt                  *int64   `json:"updated_at"`
	DeliveryFirstName          *string  `json:"delivery_first_name"`
	DeliveryLastName           *string  `json:"delivery_last_name"`
	CachedTotal                *int     `json:"cached_total"`
	SavedTax                   *int     `json:"saved_tax"`
	PromoCodeID                *int     `json:"promo_code_id"`
	MypizzaFees                *int     `json:"mypizza_fees"`
	AdminID                    *int     `json:"admin_id"`
	EmailStatus                *string  `json:"email_status"`
	ApprovalStatus             *string  `json:"approval_status"`
	ReviewedAt                 *int64   `json:"reviewed_at"`
	VoidedAt                   *int64   `json:"voided_at"`
	PromoOptIn                 *int     `json:"promo_opt_in"`
	ApprovalScore              *int     `json:"approval_score"`
	VoidOrder                  *string  `json:"void_order"`
	TransmittedBy              *string  `json:"transmitted_by"`
	AnalyticsCustomerID        *int     `json:"analytics_customer_id"`
	ProgressStep               *string  `json:"progress_step"`
	Campaign                   *string  `json:"campaign"`
	CachedSubtotal             *int     `json:"cached_subtotal"`
	CachedTax                  *int     `json:"cached_tax"`
	CachedTip                  *int     `json:"cached_tip"`
	CachedDeliveryFee          *int     `json:"cached_delivery_fee"`
	CachedShopAdjustmentAmount *int     `json:"cached_shop_adjustment_amount"`
	TransmittedAt              *int64   `json:"transmitted_at"`
	ReceivedAt                 *int64   `json:"received_at"`
	CachedSliceDiscountsAmount *int     `json:"cached_slice_discounts_amount"`
	AcknowledgedAt             *int64   `json:"acknowledged_at"`
	CachedSliceCreditsAmount   *int     `json:"cached_slice_credits_amount"`
	ConfirmedBy                *string  `json:"confirmed_by"`
	UUID                       string   `json:"uuid"`
	DeliveryID                 *string  `json:"delivery_id"`
	CustomerOrigin             *string  `json:"customer_origin"`
	DeliveryProvider           *string  `json:"delivery_provider"`
	Total                      *int     `json:"total"`
}
